version: "3"
services:
  chirpstack-packet-multiplexer:
    expose:
      - "1700/udp"
    ports:
    - 1700/udp    
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-packet-multiplexer
