version: "3"
services:
  chirpstack-packet-multiplexer:   
    ports:
      - 1700:1700/udp
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-packet-multiplexer
      - ./config/chirpstack-packet-multiplexer.toml:/etc/chirpstack-packet-multiplexer/chirpstack-packet-multiplexer.toml
